### ISSUE TITLE
AMDS-Scaler Trigger/Dwell Acquisition State

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/AcquamanDataServer#103]
My initial implementation isn't waiting for the PVs to monitor to claim the acquisition state has changed. We need to do this.

**Comment by davidChevrier** [comment]
@XuetaoLiu-CLS While you're in here, can you look at the enable PVs on the BL1611-ID-1:AMDS:scaler side. They don't appear to be getting updated correctly. You can caput to the PVs to change them, but they aren't getting set on startup.

**Comment by XuetaoLiu-S** [comment]
https://github.com/acquaman/AcquamanDataServer/pull/130

Time Estimates: 1 week
