### ISSUE TITLE
AMDS-Amptek Change Trigger Dwell to use AMDS-Scaler Style Communication

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/AcquamanDataServer#126]
The AMDS-Scaler uses a much clearer algorithm to generate trigger/dwell data. The AMDS-Amptek code needs to be updated to move to this paradigm and remove a lot of unnecessary code in both the AmptekSDD123 classes and AMDSBufferGroup.

**Comment by XuetaoLiu-S** [comment]
Time Estimate: 2 hours

@davidChevrier you might want to add your time for this as well.

**Comment by dretrex** [comment]
If the issue is in pull request you can probably close this issue now too.
