### ISSUE TITLE
Changes made during deploy Jan 18th 2016

### ISSUE THREAD

**Issue by iainworkman** [acquaman/AcquamanDataServer#131]
- Renamed duplicate instance of define directive AMDS_DWELL_DETECTOR_ALT_PV_NOT_CONNECTED to AMDS_DWELL_DETECTOR_ALT_PV_CONNECTED in AMDSDwellDetector

**Comment by XuetaoLiu-S** [comment]
@iainworkman This is fixed in $103 already. Maybe it is not merged in properly?

**Comment by iainworkman** [comment]
https://github.com/acquaman/AcquamanDataServer/blob/master/source/Detector/AMDSDwellDetector.h#L8

That is from the current master branch
Do you want to check over your code base there and make sure everything you wanted made it into #103

**Comment by XuetaoLiu-S** [comment]
I see. I committed to my local branch for that changes. But forgot to push it.

Everything else looks good.

**Comment by iainworkman** [comment]
Okay, I'll just fix it here in place then.

**Comment by XuetaoLiu-S** [comment]
@iainworkman this can be closed now, right?

**Comment by iainworkman** [comment]
Yep, will close it now.
