### ISSUE TITLE
Continuous Data request for Amptek data buffer doesn't work as expected

### ISSUE THREAD

**Issue by XuetaoLiu-S** [acquaman/AcquamanDataServer#49]
When sending continuous data request for Amptek data buffer, the server side doesn't update as expected and will disconnect for some reason unknown, which will leave the client side with one orphaned  connection.

**Comment by davidChevrier** [comment]
I changed a lot of code and didn't give an effort to keeping this request in lock step with my updates. It doesn't surprise me it's not working. Sorry.

**Comment by XuetaoLiu-S** [comment]
Took 2 days to tackle and fix this issue
