### ISSUE TITLE
AMDS: Network Session Signals

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/AcquamanDataServer#83]
In doing some early testing, I noticed that I tried to incorrectly connect to either networkSessionOpening() or networkSessionOpened(). After some digging I found that those signals only **might** be emitted. There really needs to be a final signal given that tells whatever listening to the AMDSClientAppController that it's safe to proceed. It can be networkSessionOpened(), or some other signal, but there should be only one "okay you're good to go now" signal that gets emitted whether a network session is required or not.

**Comment by XuetaoLiu-S** [comment]
Time Estimate: 2 hours
