### ISSUE TITLE
Options for debug level

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/AcquamanDataServer#87]
Right now the AMDS framework is a chatty Kathy on stdout.
In some ways this is very useful for debugging. On the other hand, writing to stdout is expensive and slow. I'm going to implement a debug level setting and (for now) just implement 0 (none) and 1 (all). We can figure out differentiated levels if need be so that debugging can be done in real time. In the future, this value could be set via a PV at run time.

**Comment by XuetaoLiu-S** [comment]
Time Estimates: 2 hours
