### ISSUE TITLE
Amptek AMDS Testing

### ISSUE THREAD

**Issue by davidChevrier** [acquaman/AcquamanDataServer#92]
@XuetaoLiu-CLS is in the process of separating the ampteks and the scaler, so we can run them on different machines.
The amptek is showing a lot more "PACKET QUEUE BUSY" messages than it used to. If this persists after the split of the applications, then we'll need to get @iainworkman to help @dretrex configure his computer's interface to do the multi-interface thing for the ampteks. Then @dretrex and @XuetaoLiu-CLS can use Sampler and Leaks to see what's going on.

**Comment by XuetaoLiu-S** [comment]
@davidChevrier @dretrex 
I saw `PACKET QUEUE BUSY` when I run the AMDS Amptek server on one OPI. But it won't appear on the designated IOC1611-406. It might be a connection issue?

**Comment by davidChevrier** [comment]
Done in 3ab72c71c0f960946cad3aaba99f9ae1cf3f082b
Issues were related to new'd but not delete'd AMDSFlatArray, QByteArray append issues, and bug in command request/response matching.
